version: '3'
services:
  server:
    build:
      context: ./Server
    volumes:
      - ./Server/:/usr/src/app
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    # Other configurations...

  web:
    build:
     context: ./Web
    volumes:
      - ./Web/:/usr/src/app
    depends_on:
      - server
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3001:3001"

    # Other configurations...
