version: '3'
services:
  server:
    build:
      context: ./Server
    volumes:
      - ./Server/:/usr/src/app
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"

  web:
    build:
     context: ./Web
    volumes:
      - ./Web/:/usr/src/app
    depends_on:
      - server
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_BACKEND_URL: http://server:3000
    ports:
      - "3001:3001"

  proxy: 
    build:
      context: ./Proxy
    depends_on:
      - server
      - web
    ports:
      - "80:80"