FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS common
COPY --from=deps /app/packages/common/node_modules/ /app/packages/common/node_modules
COPY --from=build /app/packages/common/dist /app/packages/common/dist

FROM common AS server
COPY --from=prod-deps /app/packages/server/node_modules/ /app/packages/server/node_modules
COPY --from=build /app/packages/server/dist /app/packages/server/dist
WORKDIR /app/packages/server
CMD [ "pnpm", "dev" ]

FROM common AS web
COPY --from=prod-deps /app/packages/web/node_modules/ /app/packages/web/node_modules
COPY --from=build /app/packages/web/dist /app/packages/web/dist
WORKDIR /app/packages/web
CMD [ "pnpm", "start" ]

