version: '3'
services:
  server:
    build:
      target: server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/caden/.local/share/pnpm/store:/pnpm/store
      - ./packages/server:/app

  web:
    build:
     target: web
     dockerfile: Dockerfile.dev
    volumes:
      - /home/caden/.local/share/pnpm/store:/pnpm/store
      - ./packages/web:/app

  #proxy: 
  #  build:
  #    context: ./proxy
    #depends_on:
    #  - server
    #  - web
    #ports:
     # - "80:80"